### PR TITLE
chore: update gradle and velocity repo

### PR DESCRIPTION
**Pull request by RealBauHD**

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
Good catch for the repo changes and upgraded dependencies (I was sure I had updated Gradle in my last commit but turns out I forgot 😅)

just about the `version.toml`, usually I think it’s an interesting feature especially when lots of dependencies are duplicated, but here it mixes unrelated dependencies between platforms all in the same place, where before they were each confined to the `build.gradle` of the module. And also using different versions between modules is expected : for example an older version of Gson is bundled with old Minecraft versions, so it shouldn’t be the last version, but when we are bundling it we no longer have this constraint

**Comment by RealBauHD** [comment]
I overlooked that with gson, does that apply to others? 
We could differentiate between the individual modules with empty lines and comments, since dependencies like nlogin are almost everywhere.

**Comment by MrMicky-FR** [comment]
Unless I missed one, isn't nLogin the only dependency included more than twice ? And the majority of dependencies are only included once

**Comment by RealBauHD** [comment]
netty, shadow and blossom

**Comment by MrMicky-FR** [comment]
I don't see where one of them is included at least three times (so more than twice) 😅 I see the following:
* Shadow: 2x (Universal & Universal Legacy)
* Blossom: 2x (Sponge Legacy & Velocity)

And for Netty indeed is included 3 times, but no more than twice with the same version (for compatibility, same as Gson)

**Comment by RealBauHD** [comment]
You're right, should I revert the libs.versions.toml use, so you could push the other changes?

**Comment by MrMicky-FR** [comment]
Yes would be perfect !

**Pull request merged**
